'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
(async()=>{
 const listeners=new Set(),frames=[],requests=[],timers=new Map();let timerId=0;
 const window={addEventListener:(type,fn)=>listeners.add(fn),removeEventListener:(type,fn)=>listeners.delete(fn)};
 const document={createElement:()=>({contentWindow:{},remove(){this.removed=true;}}),body:{append:frame=>frames.push(frame)}};
 const sandbox={window,document,URL,crypto:crypto.webcrypto,location:{origin:'https://school.example'},setTimeout:(fn)=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id)};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync('cloud-bridge.js','utf8'),sandbox);
 const bridge=window.createAppsScriptBridge('https://script.google.com/macros/s/test/exec');
 const response=bridge.send({action:'save',record:{id:'test-attempt'}});
 const channel=new URL(frames[0].src).searchParams.get('channel');
 const source={get parent(){throw Error('Opaque Google frame tree');},postMessage:(message,origin)=>requests.push({message,origin})};
 const emit=(origin,from,data)=>{for(const listener of [...listeners])listener({origin,source:from,data});};
 emit('https://attacker.example',source,{type:'vl2-ready',channel});
 emit('https://script.googleusercontent.com',source,{type:'vl2-ready',channel:crypto.randomUUID()});
 emit('https://script.googleusercontent.com',window,{type:'vl2-ready',channel});
 assert.equal(requests.length,0,'untrusted origin, wrong nonce and own-window source rejected');
 emit('https://script.googleusercontent.com',source,{type:'vl2-ready',channel});
 await Promise.resolve();await Promise.resolve();
 assert.equal(requests[0].message.type,'vl2-connected');
 const request=requests.find(r=>r.message.type==='vl2-request').message;
 emit('https://script.googleusercontent.com',{}, {type:'vl2-response',channel,id:request.id,result:{ok:true,id:'forged'}});
 emit('https://attacker.example',source,{type:'vl2-response',channel,id:request.id,result:{ok:true,id:'forged'}});
 emit('https://script.googleusercontent.com',source,{type:'vl2-response',channel,id:'wrong-request',result:{ok:true,id:'forged'}});
 assert.equal(timers.size,1,'forged replies cannot complete request');
 emit('https://script.googleusercontent.com',source,{type:'vl2-response',channel,id:request.id,result:{ok:true,id:'test-attempt'}});
 assert.equal((await response).id,'test-attempt');assert.equal(timers.size,0);
 console.log('PASS: opaque Google frame ancestry supported; origin, channel, pinned source and request-ID validation retained. Simulated bridge only.');
})().catch(e=>{console.error(e);process.exitCode=1});
